### ISSUE TITLE
How do i download the .exe version of the wrapper?

### ISSUE THREAD

**Issue by Hashtop** [UnleavenedEagle/SimpleWrapperLauncher#2]
Help, i'm new in github.

**Comment by UnleavenedEagle** [comment]
On the main page there is a 'Releases' option in the bar which takes you [here](https://github.com/UnleavenedEagle/SimpleWrapperLauncher/releases). There you can download the .exe file.

There is also another good method to achieve the same thing, you could try that out as well:
https://steamcommunity.com/sharedfiles/filedetails/?id=1970276543
